# Azure Pipelines
# TODO(lizan): Consider rolling all presubmit jobs into one file.
trigger:
- win

jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: "windows-latest"

  steps:
    - powershell: |
        .\ci\windows_ci_setup.ps1
        Write-Host "##vso[task.prependpath]$env:TOOLS_BIN_DIR"
      displayName: "Install dependencies"
      env:
        TOOLS_BIN_DIR: $(Pipeline.Workspace)\bin
    - bash: |
        ls -la "/c/Program Files (x86)"
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
        "C:\Program Files\Git\bin\bash.exe" ci\windows_ci_steps.sh
      displayName: "Run Windows CI"
